"""init database models

Revision ID: 1667e094ef9e
Revises: 
Create Date: 2026-03-20 22:33:34.798671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1667e094ef9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('id_bank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('bankers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', 'is_deleted', name='unique_name_bankers'),
    schema='public'
    )
    op.create_table('benefit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpnj', sa.String(length=14), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpnj'),
    schema='public'
    )
    op.create_table('flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('loan_operation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('is_inactive', sa.Boolean(), nullable=True),
    sa.Column('is_status', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'is_deleted', name='unique_rooms_name_is_deleted'),
    schema='public'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('lastname', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=True),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('typecontract', sa.String(length=30), nullable=False),
    sa.Column('session_token', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_block', sa.Boolean(), nullable=True),
    sa.Column('is_acctive', sa.Boolean(), nullable=True),
    sa.Column('is_comission', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_first_acess', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('reset_password_at', sa.DateTime(), nullable=True),
    sa.Column('reset_password_by', sa.Integer(), nullable=True),
    sa.Column('action_reset_password_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    schema='public'
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_pis', sa.CHAR(length=20), nullable=False, comment='Número do PIS/PASEP (11 dígitos)'),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('situacao_cadastro', sa.String(length=20), server_default='ativo', nullable=False),
    sa.Column('carga_horaria_semanal', sa.Numeric(precision=5, scale=2), server_default='44.0', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['public.company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['public.user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['public.user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['public.user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('numero_pis'),
    schema='public'
    )
    op.create_table('financial_agreements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('banker_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['banker_id'], ['public.bankers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('flags_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flag_id'], ['public.flags.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('obtian_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_report', sa.String(length=20), nullable=False),
    sa.Column('name_customer', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=250), nullable=True),
    sa.Column('number_proposal', sa.String(length=250), nullable=True),
    sa.Column('table_code', sa.String(length=250), nullable=True),
    sa.Column('flat', sa.Float(), nullable=True),
    sa.Column('value_operation', sa.String(length=250), nullable=True),
    sa.Column('is_validated', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_payment', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_customer'),
    sa.UniqueConstraint('name_report'),
    schema='public'
    )
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('rg_documento', sa.String(length=20), nullable=True),
    sa.Column('naturalidade', sa.String(length=100), nullable=True),
    sa.Column('cidade_naturalidade', sa.String(length=100), nullable=True),
    sa.Column('uf_naturalidade', sa.String(length=100), nullable=True),
    sa.Column('orgao_emissor', sa.String(length=100), nullable=True),
    sa.Column('uf_emissor', sa.String(length=2), nullable=True),
    sa.Column('nome_mae', sa.String(length=100), nullable=True),
    sa.Column('nome_pai', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=100), nullable=True),
    sa.Column('numero_endereco', sa.String(length=100), nullable=True),
    sa.Column('complemento_endereco', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('valor_salario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salario_liquido', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('telefone', sa.String(length=100), nullable=True),
    sa.Column('telefone_residencial', sa.String(length=100), nullable=True),
    sa.Column('telefone_comercial', sa.String(length=100), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=True),
    sa.Column('cep', sa.String(length=100), nullable=True),
    sa.Column('uf_cidade', sa.String(length=100), nullable=True),
    sa.Column('observe', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    schema='public'
    )
    op.create_table('rooms_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rooms_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_inactive', sa.Boolean(), nullable=True),
    sa.Column('is_status', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rooms_id'], ['public.rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'rooms_id', name='unique_user_room'),
    schema='public'
    )
    op.create_table('walleft',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_valided', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('flags_processing_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_payment', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flag_id'], ['public.flags.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['public.proposal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('action_at', sa.Integer(), nullable=True),
    sa.Column('action_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['public.proposal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('manage_operational',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('number_proposal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['public.proposal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('payments_comission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value_operation', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_valided', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['flag_id'], ['public.flags.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['public.proposal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('proposal_benefit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('benefit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['benefit_id'], ['public.benefit.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['public.proposal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('proposal_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aguardando_digitacao', sa.Boolean(), nullable=False),
    sa.Column('pendente_digitacao', sa.Boolean(), nullable=False),
    sa.Column('contrato_em_digitacao', sa.Boolean(), nullable=False),
    sa.Column('aceite_feito_analise_banco', sa.Boolean(), nullable=False),
    sa.Column('contrato_pendente_banco', sa.Boolean(), nullable=False),
    sa.Column('aguardando_pagamento', sa.Boolean(), nullable=False),
    sa.Column('contrato_pago', sa.Boolean(), nullable=False),
    sa.Column('contrato_reprovado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('action_at', sa.DateTime(), nullable=True),
    sa.Column('action_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['public.proposal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('proposal_wallet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agencia_banco', sa.String(length=100), nullable=False),
    sa.Column('pix_chave', sa.String(length=120), nullable=False),
    sa.Column('numero_conta', sa.String(length=20), nullable=False),
    sa.Column('agencia_dv', sa.String(length=10), nullable=False),
    sa.Column('agencia_op', sa.String(length=10), nullable=False),
    sa.Column('agency_dvop', sa.String(length=10), nullable=False),
    sa.Column('tipo_conta', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('tipo_pagamento', sa.String(length=50), nullable=False),
    sa.Column('bank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank'], ['public.bank.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['public.proposal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('service_provided',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor_operacao', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_valided', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['public.proposal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('tables_finance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('type_table', sa.String(length=250), nullable=True),
    sa.Column('table_code', sa.String(length=250), nullable=True),
    sa.Column('start_term', sa.String(length=250), nullable=True),
    sa.Column('end_term', sa.String(length=250), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('is_status', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('financial_agreements_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.String(length=250), nullable=True),
    sa.Column('start_rate', sa.String(length=250), nullable=True),
    sa.Column('end_rate', sa.String(length=250), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['financial_agreements_id'], ['public.financial_agreements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('proposal_loan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('loan_operation_id', sa.Integer(), nullable=False),
    sa.Column('senha_servidor', sa.String(length=40), nullable=False),
    sa.Column('matricula', sa.String(length=40), nullable=False),
    sa.Column('data_dispacho', sa.DateTime(), nullable=False),
    sa.Column('margem', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prazo_inicio', sa.Integer(), nullable=False),
    sa.Column('prazo_fim', sa.Integer(), nullable=False),
    sa.Column('valor_operacao', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('financial_agreements_id', sa.Integer(), nullable=False),
    sa.Column('tables_finance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['financial_agreements_id'], ['public.financial_agreements.id'], ),
    sa.ForeignKeyConstraint(['loan_operation_id'], ['public.loan_operation.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['public.proposal.id'], ),
    sa.ForeignKeyConstraint(['tables_finance_id'], ['public.tables_finance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal_loan', schema='public')
    op.drop_table('tables_finance', schema='public')
    op.drop_table('service_provided', schema='public')
    op.drop_table('proposal_wallet', schema='public')
    op.drop_table('proposal_status', schema='public')
    op.drop_table('proposal_benefit', schema='public')
    op.drop_table('payments_comission', schema='public')
    op.drop_table('manage_operational', schema='public')
    op.drop_table('history', schema='public')
    op.drop_table('flags_processing_payments', schema='public')
    op.drop_table('walleft', schema='public')
    op.drop_table('rooms_users', schema='public')
    op.drop_table('proposal', schema='public')
    op.drop_table('obtian_report', schema='public')
    op.drop_table('flags_users', schema='public')
    op.drop_table('financial_agreements', schema='public')
    op.drop_table('employee', schema='public')
    op.drop_table('user', schema='public')
    op.drop_table('rooms', schema='public')
    op.drop_table('role', schema='public')
    op.drop_table('loan_operation', schema='public')
    op.drop_table('flags', schema='public')
    op.drop_table('company', schema='public')
    op.drop_table('benefit', schema='public')
    op.drop_table('bankers', schema='public')
    op.drop_table('bank', schema='public')
    # ### end Alembic commands ###
