"""Add new tables in databasemanager

Revision ID: 2357782fc459
Revises: ac1a1f3fe450
Create Date: 2026-04-27 16:21:17.062824

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2357782fc459'
down_revision: Union[str, Sequence[str], None] = 'ac1a1f3fe450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'bankers',
        sa.Column('name', sa.String(length=20), nullable=False),
        sa.Column('created_by', sa.Uuid(), nullable=False),
        sa.Column(
            'id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['employees.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_bankers_created_by'), 'bankers', ['created_by'], unique=False
    )
    op.create_table(
        'rooms',
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.Column('created_by', sa.Uuid(), nullable=False),
        sa.Column(
            'id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['employees.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_rooms_created_by'), 'rooms', ['created_by'], unique=False)
    op.create_table(
        'financial_agreements',
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.Column('bankers_id', sa.Uuid(), nullable=False),
        sa.Column('created_by', sa.Uuid(), nullable=False),
        sa.Column(
            'id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['bankers_id'],
            ['bankers.id'],
        ),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['employees.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_financial_agreements_created_by'),
        'financial_agreements',
        ['created_by'],
        unique=False,
    )
    op.create_table(
        'proposals',
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.Column(
            'document',
            sa.Enum(
                'CPF',
                'CNPJ',
                'RG',
                'CNH',
                'PASSPORT',
                'DRIVER_LICENSE',
                'OTHER',
                name='documenttype',
            ),
            nullable=True,
        ),
        sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('financial_agreements_id', sa.Uuid(), nullable=False),
        sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True),
        sa.Column('email', sa.String(length=100), nullable=True),
        sa.Column('cpf', sa.String(length=20), nullable=False),
        sa.Column('place_of_birth', sa.String(length=100), nullable=True),
        sa.Column('birth_city', sa.String(length=100), nullable=True),
        sa.Column('birth_state', sa.String(length=100), nullable=True),
        sa.Column('rg_document', sa.String(length=100), nullable=True),
        sa.Column('issuing_authority', sa.String(length=20), nullable=True),
        sa.Column('issuing_state', sa.String(length=2), nullable=True),
        sa.Column('mother_name', sa.String(length=100), nullable=True),
        sa.Column('father_name', sa.String(length=100), nullable=True),
        sa.Column('neighborhood', sa.String(length=100), nullable=True),
        sa.Column('address', sa.String(length=200), nullable=True),
        sa.Column('address_number', sa.String(length=20), nullable=True),
        sa.Column('address_complement', sa.String(length=200), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('state', sa.String(length=2), nullable=True),
        sa.Column('zip_code', sa.String(length=20), nullable=True),
        sa.Column('gross_salary', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('net_salary', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('mobile_phone', sa.String(length=20), nullable=True),
        sa.Column('home_phone', sa.String(length=20), nullable=True),
        sa.Column('work_phone', sa.String(length=20), nullable=True),
        sa.Column('notes', sa.String(length=300), nullable=True),
        sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.Uuid(), nullable=False),
        sa.Column(
            'id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['employees.id'],
        ),
        sa.ForeignKeyConstraint(
            ['financial_agreements_id'],
            ['financial_agreements.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_proposals_created_by'), 'proposals', ['created_by'], unique=False
    )
    op.create_table(
        'proposal_acounts',
        sa.Column('bank_agency', sa.String(length=100), nullable=True),
        sa.Column('pix_key', sa.String(length=120), nullable=True),
        sa.Column('account_number', sa.String(length=20), nullable=True),
        sa.Column('agency_digit', sa.String(length=10), nullable=True),
        sa.Column('agency_operation', sa.String(length=10), nullable=True),
        sa.Column('agency_operation_digit', sa.String(length=10), nullable=True),
        sa.Column('account_type', sa.String(length=50), nullable=True),
        sa.Column('payment_type', sa.String(), nullable=True),
        sa.Column('bank_id', sa.Uuid(), nullable=True),
        sa.Column('proposal_id', sa.Uuid(), nullable=True),
        sa.Column('created_by', sa.Uuid(), nullable=False),
        sa.Column(
            'id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['bank_id'],
            ['bankers.id'],
        ),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['employees.id'],
        ),
        sa.ForeignKeyConstraint(
            ['proposal_id'],
            ['proposals.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_proposal_acounts_created_by'),
        'proposal_acounts',
        ['created_by'],
        unique=False,
    )
    op.create_table(
        'proposal_documents',
        sa.Column('proposal_id', sa.Uuid(), nullable=False),
        sa.Column('document_path', sa.String(), nullable=False),
        sa.Column('created_by', sa.Uuid(), nullable=False),
        sa.Column(
            'id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['employees.id'],
        ),
        sa.ForeignKeyConstraint(
            ['proposal_id'],
            ['proposals.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_proposal_documents_created_by'),
        'proposal_documents',
        ['created_by'],
        unique=False,
    )
    op.create_table(
        'proposal_loan_model',
        sa.Column('server_password', sa.String(length=40), nullable=True),
        sa.Column('registration_number', sa.String(length=40), nullable=True),
        sa.Column('dispatch_date', sa.DateTime(), nullable=True),
        sa.Column('available_margin', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'WAITING_TYPING',
                'TYPING_PENDING',
                'CONTRACT_IN_TYPING',
                'BANK_ANALYSIS_ACCEPTED',
                'BANK_PENDING',
                'WAITING_PAYMENT',
                'PAID',
                'REJECTED',
                name='proposalloanstatus',
            ),
            nullable=True,
        ),
        sa.Column('term_start', sa.Integer(), nullable=True),
        sa.Column('term_end', sa.Integer(), nullable=True),
        sa.Column('operation_amount', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('proposal_id', sa.Uuid(), nullable=True),
        sa.Column('finance_table_id', sa.Integer(), nullable=True),
        sa.Column('financial_agreement_id', sa.Uuid(), nullable=True),
        sa.Column('loan_operation_id', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.Uuid(), nullable=False),
        sa.Column(
            'id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['employees.id'],
        ),
        sa.ForeignKeyConstraint(
            ['financial_agreement_id'],
            ['financial_agreements.id'],
        ),
        sa.ForeignKeyConstraint(
            ['proposal_id'],
            ['proposals.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_proposal_loan_model_created_by'),
        'proposal_loan_model',
        ['created_by'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_proposal_loan_model_created_by'), table_name='proposal_loan_model'
    )
    op.drop_table('proposal_loan_model')
    op.drop_index(
        op.f('ix_proposal_documents_created_by'), table_name='proposal_documents'
    )
    op.drop_table('proposal_documents')
    op.drop_index(op.f('ix_proposal_acounts_created_by'), table_name='proposal_acounts')
    op.drop_table('proposal_acounts')
    op.drop_index(op.f('ix_proposals_created_by'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(
        op.f('ix_financial_agreements_created_by'), table_name='financial_agreements'
    )
    op.drop_table('financial_agreements')
    op.drop_index(op.f('ix_rooms_created_by'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_bankers_created_by'), table_name='bankers')
    op.drop_table('bankers')
    # ### end Alembic commands ###
