"""add unique name in rooms

Revision ID: 28fb9b0aaf72
Revises: 8bc31b7c0d06
Create Date: 2026-05-16 23:58:42.932700

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '28fb9b0aaf72'
down_revision: Union[str, Sequence[str], None] = '8bc31b7c0d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'rooms', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    # ### end Alembic commands ###
