"""Add unique name in table banker

Revision ID: 877de01c4726
Revises: 2357782fc459
Create Date: 2026-04-27 17:37:56.007208

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '877de01c4726'
down_revision: Union[str, Sequence[str], None] = '2357782fc459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bankers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bankers', type_='unique')
    # ### end Alembic commands ###
