"""Add document in relashtions employee

Revision ID: ac1a1f3fe450
Revises: 5932fb4affaa
Create Date: 2026-04-05 18:33:33.555076

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac1a1f3fe450'
down_revision: Union[str, Sequence[str], None] = '5932fb4affaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('document', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'employees', ['document'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'document')
    # ### end Alembic commands ###
