from enum import Enum


class ProposalLoanStatus(Enum):
    WAITING_TYPING = 'WAITING_TYPING'
    TYPING_PENDING = 'TYPING_PENDING'
    CONTRACT_IN_TYPING = 'CONTRACT_IN_TYPING'
    BANK_ANALYSIS_ACCEPTED = 'BANK_ANALYSIS_ACCEPTED'
    BANK_PENDING = 'BANK_PENDING'
    WAITING_PAYMENT = 'WAITING_PAYMENT'
    PAID = 'PAID'
    REJECTED = 'REJECTED'
